CREATE TABLE usuarios (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    data_nascimento DATE NOT NULL,
    genero ENUM('MASCULINO', 'FEMININO', 'NAO_BINARIO', 'OUTROS') DEFAULT 'OUTROS',
    estado_emocional ENUM('FELIZ', 'TRISTE', 'ANSIOSO', 'CANSADO', 'OUTROS') NOT NULL,
    atividade_realizada ENUM('EXERCICIO', 'LEITURA', 'TRABALHO', 'SOCIALIZAR', 'ASSISTIR_TV', 'MEDITAR', 'OUTROS') NOT NULL
);
